/**
 * MINT.md — project rules file.
 *
 * Auto-generated on `mint init` with detected project patterns.
 * User can edit manually. Injected into every prompt as system context.
 */
import { readFile, writeFile, stat, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import type { ProjectIndex } from './indexer.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ProjectRules {
  raw: string;
  sourcePath: string;
  loadedAt: number;
}

// ─── Cache ───────────────────────────────────────────────────────────────────

interface CacheEntry {
  data: ProjectRules;
  mtime: number;
}

const cache = new Map<string, CacheEntry>();

// ─── Load ────────────────────────────────────────────────────────────────────

/**
 * Search for MINT.md in standard locations (first found wins):
 *   1. {cwd}/MINT.md
 *   2. {cwd}/.mint/MINT.md
 *
 * Caches with mtime invalidation — safe to call on every agent iteration.
 */
export async function loadProjectRules(cwd: string): Promise<ProjectRules | null> {
  const candidates = [
    join(cwd, 'MINT.md'),
    join(cwd, '.mint', 'MINT.md'),
  ];

  for (const candidatePath of candidates) {
    try {
      const stats = await stat(candidatePath);
      const mtime = stats.mtimeMs;

      // Cache hit
      const cached = cache.get(candidatePath);
      if (cached && cached.mtime === mtime) {
        return cached.data;
      }

      // Cache miss or stale
      const raw = await readFile(candidatePath, 'utf-8');
      const data: ProjectRules = { raw, sourcePath: candidatePath, loadedAt: Date.now() };
      cache.set(candidatePath, { data, mtime });
      return data;
    } catch {
      continue;
    }
  }

  return null;
}

/**
 * Format MINT.md content for injection into the system prompt.
 */
export function formatProjectRulesForPrompt(rules: ProjectRules): string {
  return `<project_rules source="${rules.sourcePath}">\n${rules.raw}\n</project_rules>\n`;
}

// ─── Auto-generate ──────────────────────────────────────────────────────────

/**
 * Auto-generate a MINT.md based on detected project patterns.
 * Only creates it if it doesn't already exist.
 */
export async function generateProjectRules(cwd: string, index: ProjectIndex): Promise<string> {
  // Don't overwrite existing
  const existing = await loadProjectRules(cwd);
  if (existing) return existing.sourcePath;

  const sections: string[] = [];

  // Header
  sections.push('# MINT.md — Project Rules');
  sections.push('');
  sections.push('> Auto-generated by `mint init`. Edit freely — this file is injected into every prompt.');
  sections.push('');

  // Project overview
  sections.push('## Project');
  sections.push('');
  sections.push(`- **Language:** ${index.language}`);
  sections.push(`- **Files:** ${index.totalFiles}`);
  sections.push(`- **LOC:** ${index.totalLOC.toLocaleString()}`);

  // Detect framework
  const framework = detectFramework(cwd);
  if (framework) {
    sections.push(`- **Framework:** ${framework}`);
  }

  // Detect package manager
  const pkgManager = detectPackageManager(cwd);
  if (pkgManager) {
    sections.push(`- **Package Manager:** ${pkgManager}`);
  }

  sections.push('');

  // Rules section
  sections.push('## Rules');
  sections.push('');
  sections.push('- Be concise. Prefer direct code changes over explanations.');
  sections.push('- Use `read_file` before editing — never edit blindly.');
  sections.push('- Run tests after making changes.');
  sections.push('- Keep changes minimal and focused on the task.');
  sections.push('');

  // Architecture section — list central files
  sections.push('## Architecture');
  sections.push('');
  sections.push('Key files (edit these carefully):');

  const centralFiles = findCentralFiles(index);
  for (const f of centralFiles.slice(0, 10)) {
    const info = index.files[f];
    sections.push(`- \`${f}\` — ${info?.summary ?? ''}`);
  }
  sections.push('');

  // Commands section — detect from package.json
  const commands = await detectCommands(cwd);
  if (commands.length > 0) {
    sections.push('## Commands');
    sections.push('');
    for (const cmd of commands) {
      sections.push(`- \`${cmd.command}\` — ${cmd.description}`);
    }
    sections.push('');
  }

  // Gotchas section (placeholder)
  sections.push('## Gotchas');
  sections.push('');
  sections.push('<!-- Add project-specific pitfalls here -->');
  sections.push('');

  const content = sections.join('\n');

  // Write to MINT.md at project root
  const outPath = join(cwd, 'MINT.md');
  await writeFile(outPath, content, 'utf-8');

  return outPath;
}

// ─── Detection helpers ──────────────────────────────────────────────────────

function detectFramework(cwd: string): string | null {
  const checks: Array<{ file: string; pattern?: RegExp; name: string }> = [
    { file: 'next.config.js', name: 'Next.js' },
    { file: 'next.config.ts', name: 'Next.js' },
    { file: 'nuxt.config.ts', name: 'Nuxt' },
    { file: 'svelte.config.js', name: 'SvelteKit' },
    { file: 'astro.config.mjs', name: 'Astro' },
    { file: 'vite.config.ts', name: 'Vite' },
    { file: 'vite.config.js', name: 'Vite' },
    { file: 'angular.json', name: 'Angular' },
    { file: 'remix.config.js', name: 'Remix' },
    { file: 'Cargo.toml', name: 'Rust/Cargo' },
    { file: 'go.mod', name: 'Go' },
    { file: 'pyproject.toml', name: 'Python' },
    { file: 'requirements.txt', name: 'Python' },
    { file: 'Gemfile', name: 'Ruby' },
    { file: 'build.gradle', name: 'Gradle' },
    { file: 'pom.xml', name: 'Maven' },
    // Landing page frameworks
    { file: 'landing/vite.config.ts', name: 'Landing (Vite + React)' },
    { file: 'landing/vite.config.js', name: 'Landing (Vite + React)' },
    { file: 'landing/package.json', name: 'Landing (React)' },
  ];

  for (const { file, name } of checks) {
    if (existsSync(join(cwd, file))) return name;
  }

  // Check package.json dependencies
  try {
    const pkg = JSON.parse(require('node:fs').readFileSync(join(cwd, 'package.json'), 'utf-8'));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps['react']) return deps['next'] ? 'Next.js + React' : 'React';
    if (deps['vue']) return 'Vue';
    if (deps['express']) return 'Express';
    if (deps['fastify']) return 'Fastify';
    if (deps['hono']) return 'Hono';
    if (deps['ink']) return 'Ink (React CLI)';
  } catch { /* no package.json */ }

  return null;
}

function detectPackageManager(cwd: string): string | null {
  if (existsSync(join(cwd, 'pnpm-lock.yaml'))) return 'pnpm';
  if (existsSync(join(cwd, 'yarn.lock'))) return 'yarn';
  if (existsSync(join(cwd, 'bun.lockb'))) return 'bun';
  if (existsSync(join(cwd, 'package-lock.json'))) return 'npm';
  return null;
}

function findCentralFiles(index: ProjectIndex): string[] {
  // Files with most imports + importedBy = most central
  const scored: Array<{ path: string; degree: number }> = [];
  for (const [path, edges] of Object.entries(index.graph)) {
    scored.push({
      path,
      degree: (edges.imports?.length ?? 0) + (edges.importedBy?.length ?? 0),
    });
  }
  scored.sort((a, b) => b.degree - a.degree);
  return scored.slice(0, 15).map(s => s.path);
}

interface CommandInfo {
  command: string;
  description: string;
}

async function detectCommands(cwd: string): Promise<CommandInfo[]> {
  const commands: CommandInfo[] = [];

  try {
    const pkg = JSON.parse(await readFile(join(cwd, 'package.json'), 'utf-8'));
    const scripts = pkg.scripts ?? {};

    const importantScripts = ['build', 'dev', 'start', 'test', 'lint', 'typecheck', 'format'];
    for (const name of importantScripts) {
      if (scripts[name]) {
        commands.push({ command: `npm run ${name}`, description: scripts[name] });
      }
    }
  } catch { /* no package.json */ }

  // Makefile
  if (existsSync(join(cwd, 'Makefile'))) {
    commands.push({ command: 'make', description: 'See Makefile for targets' });
  }

  return commands;
}

// ─── Starter skills generation ────────────────────────────────────────────

/**
 * Generate starter skill files in .mint/skills/ based on detected project type.
 * Called during `mint init`.
 */
export async function generateStarterSkills(cwd: string): Promise<string[]> {
  const skillsDir = join(cwd, '.mint', 'skills');
  await mkdir(skillsDir, { recursive: true });

  const created: string[] = [];

  // Detect project type from package.json dependencies
  let deps: Record<string, string> = {};
  let hasPackageJson = false;
  try {
    const pkg = JSON.parse(await readFile(join(cwd, 'package.json'), 'utf-8'));
    deps = { ...pkg.dependencies, ...pkg.devDependencies };
    hasPackageJson = true;
  } catch { /* no package.json */ }

  // Check for Python
  const hasPython = existsSync(join(cwd, 'requirements.txt')) ||
    existsSync(join(cwd, 'pyproject.toml')) ||
    existsSync(join(cwd, 'setup.py'));

  if (hasPackageJson && (deps['react'] || deps['next'] || deps['vue'] || deps['svelte'])) {
    const framework = deps['next'] ? 'Next.js' : deps['vue'] ? 'Vue' : deps['svelte'] ? 'Svelte' : 'React';
    const skillPath = join(skillsDir, 'react-patterns.md');
    if (!existsSync(skillPath)) {
      await writeFile(skillPath, `---
applies_to: [frontend]
---
# ${framework} Patterns
# Edit this file to teach Mint your project's conventions

- Use functional components with hooks, not class components
- Keep components small and focused (under 150 lines)
- Co-locate component, styles, and tests in the same directory
- Use TypeScript strict mode for all component props
- Prefer composition over prop drilling — use context for shared state
- Name components with PascalCase, hooks with use prefix
- Extract reusable logic into custom hooks
- Handle loading, error, and empty states in every data-fetching component
- Use semantic HTML elements (button, nav, main) over generic divs
- Keep styles scoped — avoid global CSS mutations
`, 'utf-8');
      created.push(skillPath);
    }
  }

  if (hasPackageJson && (deps['express'] || deps['fastify'] || deps['@nestjs/core'] || deps['hono'])) {
    const framework = deps['express'] ? 'Express' : deps['fastify'] ? 'Fastify' : deps['@nestjs/core'] ? 'NestJS' : 'Hono';
    const skillPath = join(skillsDir, 'api-patterns.md');
    if (!existsSync(skillPath)) {
      await writeFile(skillPath, `---
applies_to: [backend]
---
# ${framework} API Patterns
# Edit this file to teach Mint your project's conventions

- Validate all request inputs at the handler level
- Use proper HTTP status codes (201 for create, 204 for delete, 422 for validation)
- Return consistent error response shape: { error: string, code: string }
- Use middleware for cross-cutting concerns (auth, logging, rate limiting)
- Keep route handlers thin — delegate business logic to service layer
- Never expose internal errors to clients — log and return generic message
- Use async/await with proper try/catch, never unhandled promises
- Document API endpoints with JSDoc or OpenAPI annotations
- Group related routes in separate router files
- Use environment variables for all configuration, never hardcode secrets
`, 'utf-8');
      created.push(skillPath);
    }
  }

  if (hasPython) {
    const skillPath = join(skillsDir, 'python-style.md');
    if (!existsSync(skillPath)) {
      await writeFile(skillPath, `---
applies_to: [backend, testing]
---
# Python Style Guide
# Edit this file to teach Mint your project's conventions

- Follow PEP 8 style guidelines
- Use type hints for function signatures
- Prefer f-strings over .format() or % formatting
- Use dataclasses or Pydantic models for structured data
- Keep functions short and single-purpose
- Use context managers (with statements) for resource management
- Write docstrings for all public functions and classes
- Use virtual environments, never install globally
- Prefer list comprehensions over map/filter for simple transformations
- Handle exceptions specifically, never bare except
`, 'utf-8');
      created.push(skillPath);
    }
  }

  // Landing page skills
  if (existsSync(join(cwd, 'landing', 'package.json'))) {
    const skillPath = join(skillsDir, 'landing-page.md');
    if (!existsSync(skillPath)) {
      await writeFile(skillPath, `---applies_to: [frontend, landing]
---
# Landing Page Patterns
# Edit this file to teach Mint your project's conventions for the landing page

- Use functional React components with TypeScript
- Keep components small and focused (under 200 lines)
- Co-locate component, styles, and tests in the same directory
- Use Tailwind CSS for styling (if configured)
- Prefer CSS-in-JS or styled-components for complex animations
- Handle loading states and error boundaries gracefully
- Optimize images and assets for web performance
- Use semantic HTML elements (button, section, header, footer)
- Keep hero sections and CTAs above the fold
- Minimize third-party scripts and trackers
- Test responsiveness across mobile, tablet, and desktop
- Use lazy loading for non-critical assets
- Implement proper SEO meta tags in the head
- Keep bundle size under control — audit with webpack-bundle-analyzer
`, 'utf-8');
      created.push(skillPath);
    }
  }

  // Fallback: general code style
  if (created.length === 0) {
    const skillPath = join(skillsDir, 'code-style.md');
    if (!existsSync(skillPath)) {
      await writeFile(skillPath, `# Code Style Guide
# Edit this file to teach Mint your project's conventions

- Be consistent with existing code patterns in the project
- Write clear, descriptive variable and function names
- Keep functions focused — one function, one responsibility
- Add comments only for "why", not "what" — code should be self-documenting
- Handle errors explicitly, never silently swallow exceptions
- Write tests for new functionality
- Keep files under 300 lines — split when they grow
- Use constants for magic numbers and repeated strings
- Prefer immutable data structures when possible
- Review your changes before committing — remove debug artifacts
`, 'utf-8');
      created.push(skillPath);
    }
  }

  return created;
}
