import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

export type SessionTaskComplexity = 'trivial' | 'simple' | 'moderate' | 'complex';

export interface SessionMemorySnapshot {
  updatedAt: string;
  runId?: string;
  cwd: string;
  task: string;
  complexity: SessionTaskComplexity;
  filesSearched: string[];
  scopeDirectories: string[];
  entryFiles: string[];
  writeTargets: string[];
  architectPlan?: string;
  architectResearch: string[];
  builderBriefs: string[];
  finalResponseSummary?: string;
  reviewerFeedback?: string;
}

export interface SessionMemoryDocument {
  raw: string;
  sourcePaths: string[];
  loadedAt: number;
  snapshot?: SessionMemorySnapshot | null;
}

const AUTO_MEMORY_DIR = '.mint';
const AUTO_MEMORY_MARKDOWN = 'MEMORY.md';
const AUTO_MEMORY_JSON = 'memory.json';

export async function loadSessionMemory(cwd: string): Promise<SessionMemoryDocument | null> {
  const manualPath = join(cwd, 'MEMORY.md');
  const autoPath = join(cwd, AUTO_MEMORY_DIR, AUTO_MEMORY_MARKDOWN);
  const blocks: string[] = [];
  const sourcePaths: string[] = [];

  if (existsSync(manualPath)) {
    const manual = await readFile(manualPath, 'utf8');
    if (manual.trim().length > 0) {
      blocks.push(manual.trim());
      sourcePaths.push(manualPath);
    }
  }

  if (existsSync(autoPath)) {
    const auto = await readFile(autoPath, 'utf8');
    if (auto.trim().length > 0) {
      blocks.push(auto.trim());
      sourcePaths.push(autoPath);
    }
  }

  const snapshot = await loadSessionMemorySnapshot(cwd);
  if (blocks.length === 0 && !snapshot) {
    return null;
  }

  return {
    raw: blocks.join('\n\n---\n\n'),
    sourcePaths,
    loadedAt: Date.now(),
    snapshot,
  };
}

export async function loadSessionMemorySnapshot(cwd: string): Promise<SessionMemorySnapshot | null> {
  const snapshotPath = join(cwd, AUTO_MEMORY_DIR, AUTO_MEMORY_JSON);
  if (!existsSync(snapshotPath)) {
    return null;
  }

  try {
    const raw = await readFile(snapshotPath, 'utf8');
    return JSON.parse(raw) as SessionMemorySnapshot;
  } catch {
    return null;
  }
}

export function formatSessionMemoryForPrompt(memory: SessionMemoryDocument): string {
  const sourceAttr = memory.sourcePaths.length > 0
    ? memory.sourcePaths.join(',')
    : 'generated';
  return `<session_memory source="${sourceAttr}">\n${memory.raw}\n</session_memory>`;
}

export function formatSessionMemorySummary(snapshot: SessionMemorySnapshot): string {
  const parts: string[] = [
    `Last task: ${snapshot.task}`,
    snapshot.scopeDirectories.length > 0 ? `Scope: ${snapshot.scopeDirectories.join(', ')}` : '',
    snapshot.entryFiles.length > 0 ? `Entry files: ${snapshot.entryFiles.join(', ')}` : '',
    snapshot.writeTargets.length > 0 ? `Write targets: ${snapshot.writeTargets.join(', ')}` : '',
  ].filter(Boolean);
  return parts.join('\n');
}

export function getSessionMemoryCandidateFiles(snapshot: SessionMemorySnapshot | null | undefined): string[] {
  if (!snapshot) return [];
  return uniqueStrings([
    ...snapshot.entryFiles,
    ...snapshot.writeTargets,
    ...snapshot.filesSearched,
  ]).slice(0, 12);
}

export function getSessionMemoryScopeHints(snapshot: SessionMemorySnapshot | null | undefined): string[] {
  if (!snapshot) return [];
  return uniqueStrings([
    ...snapshot.scopeDirectories,
    ...snapshot.entryFiles,
    ...snapshot.writeTargets,
  ]).slice(0, 12);
}

export function isReferentialTask(task: string): boolean {
  return /\b(it|that|those|them|this|previous|previously|before|back|again|same|revert|undo|restore|old|earlier)\b|whatever was there/i.test(task);
}

export async function persistSessionMemory(
  cwd: string,
  snapshot: SessionMemorySnapshot,
): Promise<void> {
  const dir = join(cwd, AUTO_MEMORY_DIR);
  await mkdir(dir, { recursive: true });

  const markdownPath = join(dir, AUTO_MEMORY_MARKDOWN);
  const jsonPath = join(dir, AUTO_MEMORY_JSON);
  const markdown = renderSessionMemoryMarkdown(snapshot);

  await Promise.all([
    writeFile(markdownPath, markdown, 'utf8'),
    writeFile(jsonPath, JSON.stringify(snapshot, null, 2), 'utf8'),
  ]);
}

function renderSessionMemoryMarkdown(snapshot: SessionMemorySnapshot): string {
  const lines: string[] = [
    '# MEMORY.md — Session Memory',
    '',
    '> Auto-generated by Mint from the latest pipeline run. Use this to resolve follow-ups like "revert that" or "put it back".',
    '',
    '## Last Request',
    '',
    `- Updated: ${snapshot.updatedAt}`,
    snapshot.runId ? `- Run ID: ${snapshot.runId}` : '',
    `- Task: ${snapshot.task}`,
    `- Complexity: ${snapshot.complexity}`,
    '',
    '## Resolved Scope',
    '',
    snapshot.scopeDirectories.length > 0 ? `- Scope directories: ${snapshot.scopeDirectories.join(', ')}` : '- Scope directories: none',
    snapshot.entryFiles.length > 0 ? `- Entry files: ${snapshot.entryFiles.join(', ')}` : '- Entry files: none',
    snapshot.filesSearched.length > 0 ? `- Relevant files: ${snapshot.filesSearched.join(', ')}` : '- Relevant files: none',
    snapshot.writeTargets.length > 0 ? `- Write targets: ${snapshot.writeTargets.join(', ')}` : '- Write targets: none',
    '',
    '## Architect Handoff',
    '',
    snapshot.architectPlan ? snapshot.architectPlan : '- No architect plan captured.',
    '',
    '### Research',
    '',
    ...renderBulletList(snapshot.architectResearch, 'No architect research captured.'),
    '',
    '### Builder Briefs',
    '',
    ...renderBulletList(snapshot.builderBriefs, 'No builder briefs captured.'),
    '',
    '## Last Outcome',
    '',
    snapshot.finalResponseSummary ? `- Summary: ${snapshot.finalResponseSummary}` : '- Summary: none',
    snapshot.reviewerFeedback ? `- Reviewer feedback: ${snapshot.reviewerFeedback}` : '- Reviewer feedback: none',
    '',
  ];

  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === '')).join('\n');
}

function renderBulletList(items: string[], emptyText: string): string[] {
  if (items.length === 0) {
    return [`- ${emptyText}`];
  }
  return items.map((item) => `- ${item}`);
}

function uniqueStrings(values: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const value of values) {
    const normalized = value.trim();
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    result.push(normalized);
  }

  return result;
}
